// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;

/// A class that exposes all available Firebase options.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    return web;
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBvEk-UDgx5QYByPN32l_4s5DtlD9fVRE',
    appId: '1:1003971120831:android:462e1a306a93a610a2000a',
    messagingSenderId: '1003971120831',
    projectId: 'agrovet-nk1323',
    authDomain: 'agrovet-nk1323.firebaseapp.com',
    databaseURL: 'https://agrovet-nk1323.firebaseio.com',
    storageBucket: 'agrovet-nk1323.firebasestorage.app',
    measurementId: '',
  );
}
